cargo-features = ["edition2021"]

[package]
name = "counter"
version = "0.1.0"
edition = "2021"
license = "WTFPL"
publish = false

[dependencies]
borsh = "0.9"
solana-program = "=1.8.14"
thiserror = "1.0"

[lib]
crate-type = ["cdylib", "lib"]